baseURL: "https://viitetrix.github.io/nav/"  # 网站的基础URL
languageCode: "zh-CN"                        # 网站语言代码
title: "ViiTetrix 告别抓瞎"                  # 网站标题
theme: "WebStack-Hugo"                       # 使用的主题
preserveTaxonomyNames: true                  # 保留分类名称的原始大小写
disablePathToLower: true                    # 禁用URL路径自动转小写
hasCJKLanguage: true                        # 启用中日韩语言支持
publishDir: "public"                        # 生成的静态文件存放目录

disableKinds: ["taxonomy", "term"]          # 禁用分类和术语页面生成

params:
  author: "ViiTetrix"
  description: "ViiTetrix 告别抓瞎"
  upload: "https://weibo.com/viitetrix"  # 左侧导航栏的"网站提交"
  about: "https://github.com/shenweiyan/Knowledge-Garden/discussions/10"  # 左侧导航栏的"关于导航"页面(./about)
  repository: "https://github.com/shenweiyan/WebStack-Hugo"
  enablePreLoad: true  # 网站完全打开前预加载动画
  textPreLoad: "告别抓瞎"  # 预加载的动画文字, 只有当enablePreLoad=true时生效
  expandSidebar: true  # 默认展开左侧边导航栏
  logosPath: "assets/images/logos"  # 网站每个导航地址logo存放地址
  defaultLogo: "assets/images/logos/default.webp"  # logo图片资源不存在或者错误时, 默认显示的logo
  nightMode: false  # 默认站点为深色(夜间)模式
  yiyan: true  # 默认启用一言服务
  fancybox: true  # 使用 Fancybox 实现图片灯箱/放大功能

  seo:
    baiduhmid: "efccc04cb44fc49faddac5876180b369"  # 百度统计 hm.src 的 ID
    baiduSiteVer: "codeva-cCAOSG8MBO"  # 百度HTML标签验证
    tj51laid: ""  # 51.LA 网站统计
    tj51lack: ""
    GoogleAdsClient: ""  # Google AdSense

  qweather:
    key: "085791e805a24491b43b06cf58ab31e7"

  images:
    favicon: "assets/images/v-favicon.png"
    searchImageL: "assets/images/hello_world.png"  # 搜索部分浅色背景图
    searchImageD: "assets/images/hello_world.png"  # 搜索部分深色背景图
    logoExpandLight: "assets/images/v-expand-dark.png"
    logoExpandDark: "assets/images/v-expand-light.png"
    logoCollapseLight: "assets/images/v.png"
    logoCollapseDark: "assets/images/v.png"

  footer:
    copyright: |
      本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：viitetrix@gmail.com <br/>
      &copy; 2021 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) <br/>

markup:
  goldmark:
    renderer:
      unsafe: true
